version: 0.2

phases:
  build:
    commands:
      - echo "Build started on $(date)"
      - mkdir dist
      - cp assets/index.html dist/

artifacts:
  files:
    - dist/**/*
  base-directory: dist
  name: site.zip
